cc_library(
    name = "kalman_filter",
    srcs = ["kalman_filter.cc"],
    hdrs = ["kalman_filter.h"],
    deps = [
       
    ],
)

cc_binary(
    name = "kalman_test",
    srcs = ["kalman_test.cc"],

    deps = [
        ":kalman_filter",
        
    ],
)